CREATE TYPE "public"."instrument_meta_source" AS ENUM('JUSTETF', 'YAHOO', 'FMP', 'MANUAL');--> statement-breakpoint
CREATE TYPE "public"."instrument_meta_status" AS ENUM('OK', 'NOT_FOUND', 'ERROR');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "instrument_meta" (
	"isin" text PRIMARY KEY NOT NULL,
	"status" "instrument_meta_status" NOT NULL,
	"source" "instrument_meta_source",
	"asset_kind" text,
	"name" text,
	"sector" text,
	"industry" text,
	"yahoo_symbol" text,
	"yahoo_quote_symbol" text,
	"justetf_ticker" text,
	"wkn" text,
	"fund_currency" text,
	"domicile" text,
	"index_name" text,
	"investment_focus" text,
	"replication" text,
	"ter_pct" numeric,
	"distribution_policy" text,
	"distribution_frequency" text,
	"teilfreistellung_pct" integer,
	"fund_subtype" text,
	"div_trailing_12m" numeric,
	"div_trailing_12m_currency" text,
	"div_forward_rate" numeric,
	"div_forward_yield_pct" numeric,
	"ex_dividend_date" text,
	"manual_url" text,
	"raw" jsonb,
	"fail_count" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"scraped_at" timestamp,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
